### ISSUE TITLE
dnd组件内部没有根据新的state重新渲染

### ISSUE THREAD

**Issue by lyx9439** [tinper-bee/bee-dnd#2]
我在dnd组件的onStop事件里调用setState，但是组件内部并没有根据新的state重新渲染

import React, { Component } from 'react';
import { Dnd } from 'tinper-bee';

class Demo extends Component {
	constructor(props) {
		super(props);
		this.state = {
			list: [ 1, 2, 3 ]
		};
	}

	render() {
		return (
			<div style={{ width: '480px' }}>
				<Dnd list={this.state.list} />
				<button
					onClick={() => {
						this.setState({
							list: [ 1, 2, 3, 4 ]
						});
					}}
				>
					click me
				</button>
			</div>
		);
	}
}

export default Demo;

**Comment by liushaozhen** [comment]
好的，这边看一下，然后修改一下
